# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ 12.0-rm-travis ]
  pull_request:
    branches: [ 12.0-rm-travis ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Configuration
      run: |
        pip install pre-commit
        pip install black
        pip install flake8
    - name: Pre-Commit
      run:
        pre-commit run --all --show-diff-on-failure --verbose --color always
  odoo:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    env:
      TESTS: "1"
      ODOO_REPO: "odoo/odoo"
      VERSION: "12.0"
      MAKEPOT: "1"
      LINT_CHECK: "0"
      TRAVIS_HOME: "/home/runner"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Configuration
        run: |
          pip install wheel
          sudo apt install libldap2-dev nodejs libxml2-dev libxslt1-dev libevent-dev libsasl2-dev expect python3-lxml python3-libsass
      - name: Configuring tests
        run: |
          git clone --depth=1 https://github.com/tegin/maintainer-quality-tools.git -b master-github ${HOME}/maintainer-quality-tools
      - name: Install nightly
        run: |
          export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
          export TRAVIS_BUILD_DIR=${GITHUB_WORKSPACE}
          travis_install_nightly
      - name: Running test
        run: |

          export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
          export TRAVIS_BUILD_DIR=${GITHUB_WORKSPACE}
          travis_run_tests
        env:
          DB_USERNAME: "odoo"
          DB_PASSWORD: "odoo"
          DB_HOST: "localhost"
          DB_PORT: 5432
      - name: After success
        run: |
          export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
          export TRAVIS_BUILD_DIR=${GITHUB_WORKSPACE}
          travis_after_tests_success
